name: wifi_fingerprinting
description: Prototype for an indoor fingerprinting application for the University of Applied Sciences Munich.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  firebase_storage: ^4.0.1
  cloud_functions: ^0.6.0+1
  cloud_firestore: ^0.14.1+3
  uuid: ^2.2.2
  intl: ^0.16.1
  freezed_annotation: ^0.12.0
  kt_dart: ^0.8.0
  path_provider: ^1.6.22
  dartz: ^0.9.2
  rxdart: ^0.24.1
  auto_route: ^0.6.9
  flutter_bloc: ^6.0.6
  provider: ^4.3.2+2
  meta: ^1.2.3
  equatable: ^1.2.5
  get_it: ^5.0.1
  injectable: ^1.0.5
  wifi_hunter: ^1.0.3
  sembast: ^2.4.7+7
  permission_handler: ^5.0.1+1
  verve: ^0.3.2+3
  cupertino_icons: ^1.0.0
  json_annotation: ^3.1.0
  flushbar: ^1.10.4
  flutter_hooks: ^0.14.1
  image_picker: ^0.6.7+12
  positioned_tap_detector: ^1.0.3
  photo_view: ^0.10.2
  vector_math: ^2.0.8
  shared_preferences: ^0.5.12+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  auto_route_generator: ^0.6.10
  json_serializable: ^3.5.0
  flutter_launcher_icons: ^0.8.1
  dapackages: ^1.3.0
  build_runner:
    
flutter:
  uses-material-design: true
